name: Build Docker image and Push to Dev Branch

on:
  workflow_run:
    workflows: ["Release-dev"]
    types:
      - completed
    paths-ignore:
      - "**.md"
      - "**.json"

env:
  REGISTRY: jhinga
  FRONTEND_IMAGE_NAME: frontend
  BACKEND1_IMAGE_NAME: backend1
  BACKEND2_IMAGE_NAME: backend2
  DATABASE_IMAGE_NAME: database

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend1: ${{ steps.services.outputs.backend1 }}
      backend2: ${{ steps.services.outputs.backend2 }}
      frontend: ${{ steps.services.outputs.frontend }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download SHA artifact
        uses: actions/download-artifact@v4
        with:
          name: sha

      - name: Read base SHA
        id: sha
        run: |
          BASE_SHA=$(cat sha.txt)
          echo "base_sha=$BASE_SHA" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changes
        run: |
          git fetch origin
          git diff --name-only ${{ steps.sha.outputs.base_sha }} HEAD > changed_files.txt
          cat changed_files.txt

      - name: Determine changed services
        id: services
        run: |
          backend1=false
          backend2=false
          frontend=false

          while IFS= read -r file; do
            [[ "$file" == backend1/* ]] && backend1=true
            [[ "$file" == backend2/* ]] && backend2=true
            [[ "$file" == frontend/* ]] && frontend=true
          done < changed_files.txt

          echo "backend1=$backend1" >> $GITHUB_OUTPUT
          echo "backend2=$backend2" >> $GITHUB_OUTPUT
          echo "frontend=$frontend" >> $GITHUB_OUTPUT

  backend1:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend1 == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "Latest tag is $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend1
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:dev-${{ steps.get_tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:dev-latest
          # cache-from: type=local,src=/tmp/.buildx-cache-backend1
          # cache-to: type=local,dest=/tmp/.buildx-cache-backend1,mode=max

  backend2:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "Latest tag is $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend2
        uses: docker/build-push-action@v5

        with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:dev-${{ steps.get_tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:dev-latest
          # cache-from: type=local,src=/tmp/.buildx-cache-backend2
          # cache-to: type=local,dest=/tmp/.buildx-cache-backend2,mode=max

  frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    name: Frontend build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "Latest tag is $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-${{ steps.get_tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-latest
          # cache-from: type=local,src=/tmp/.buildx-cache-frontend
          # cache-to: type=local,dest=/tmp/.buildx-cache-frontend,mode=max
