name: PR check and Build Docker image and Push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

env:
  REGISTRY: jhinga
  FRONTEND_IMAGE_NAME: frontend
  BACKEND1_IMAGE_NAME: backend1
  BACKEND2_IMAGE_NAME: backend2
  DATABASE_IMAGE_NAME: database

jobs:
  pr-check:
    if: github.event_name == 'pull_request'
    name: Check PR changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Conventional Commit Lint
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,docs,style,refactor,test,chore,ci,perf,revert"

      - name: Display current branch
        run: echo "Checking PR from ${{ github.head_ref }} to ${{ github.base_ref }}"

  backend:
    if: github.event_name == 'push'
    name: Backend Build and push
    runs-on: [backend]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend1
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:dev-latest

      - name: Build & push backend1 (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:prod-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:latest

      - name: Build & push backend2 (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5

        with:
          context: .
          file: ./backend2/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:prod-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:latest

      - name: Build & push backend2
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5

        with:
          context: .
          file: ./backend2/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:dev-latest

  frontend:
    if: github.event_name == 'push'
    name: Frontend build and push
    runs-on: [frontend]
    steps:
      - name: Build & push frontend
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-latest

      - name: Build & push frontend (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:prod-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

  database:
    if: github.event_name == 'push'
    name: Database build and push
    runs-on: [frontend]
    steps:
      - name: Build & push database
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:dev-latest

      - name: Build & push database(main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:prod-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:prod-latest

      - name: Complete workflow
        run: echo "Workflow completed"
