name: PR check and Build Docker image and Push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: jhinga/frontend
  BACKEND1_IMAGE_NAME: jhinga/backend1
  BACKEND2_IMAGE_NAME: jhinga/backend2
  DATABASE_IMAGE_NAME: jhinga/database

jobs:
  pr-check:
    if: github.event_name == 'pull_request' && github.head_ref == 'feature' && github.base.ref == 'dev'
    name: Check PR changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Conventional Commit Lint
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,docs,style,refactor,test,chore,ci,perf,revert"

      - name: Display current branch
        run: echo "Checking PR from ${{ github.head_ref }} to ${{ github.base_ref }}"

  docker:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend1
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME_IMAGE_NAME }}:dev-latest

      - name: Build & push backend2
        uses: docker/build-push-action@v5
        with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND2_IMAGE_NAME_IMAGE_NAME }}:dev-latest

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME_IMAGE_NAME }}:dev-latest

      - name: Build & push database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}:dev-latest

      - name: Complete workflow
        run: echo "Workflow completed"
