name: Release-dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**.md"
      - "**.json"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save base commit SHA
        run: echo "${{ github.sha }}" > base_commit.txt

      - name: Upload base commit as artifact
        uses: actions/upload-artifact@v4
        with:
          name: base-commit
          path: base_commit.txt

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx semantic-release
